name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
jobs:
  production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout (ALL)
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy S3
        run: aws s3 sync ./ s3://static.ponegly.ph --exclude ".github/*" --acl public-read --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id EBO2K9X7ON8T --paths "/*"